site_name: sdl Documentation
site_description: "A complete documentation for the project Silkroad Dev Laravel CMS based on the framework Laravel."
site_url: "https://doc.devso.me/"
copyright: Copyright &copy; 2020 Devsome

repo_url: https://github.com/Devsome/silkroad-laravel

extra_javascript:
  - particles.min.js


theme:
  name: material
  favicon: images/favicon/favicon.ico
  logo: images/logo.svg
  features:
    - tabs
  language: en
  theme:
    features:
      - instant
    palette:
      scheme: default
      primary: indigo
      accent: blue
  custom_dir: 'docs/overrides'
  static_templates:
    - 404.html


extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/realDevsome
    - icon: fontawesome/brands/github
      link: https://github.com/Devsome

google_analytics:
  - UA-179003559-1
  - auto

# Page tree
nav:
  - Home:
    - introduction.md
    - getting-started.md
    - styling.md
  - Features:
    - features.md
  - Windows Guide:
    - windows-guide.md
